# Generated by Django 5.2.8 on 2026-01-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
