# Generated by Django 5.2.8 on 2026-01-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready to Out'), ('out', 'Out for Delivery'), ('delivered', 'Delivered')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
